### ISSUE TITLE
Support for .net version 4.5.2

### ISSUE THREAD

**Issue by jyloo** [daviddesmet/paseto-dotnet#15]
Hi again. If i have a project that targets 4.5.2, and it's quite impossible to switch to 4.7.
Is there any way that i can install paseto dot net on a .net 4.5.2 project?

**Comment by daviddesmet** [comment]
I would have to test against 4.5.2 but I don’t see any issue since NaCl.Core which is a dependency, was requested support for .NET 4.5 a while ago.

Please give me some time since I have to test with a Windows host.

**Comment by daviddesmet** [comment]
I wasn't able to support 4.5.2 due to a limitation in RSA crypto which is required in `v1.public` of Paseto.
I was able to add support for 4.6 though. It is not yet published at Nuget.

**Comment by jyloo** [comment]
@idaviddesmet 4.6 will do. May i know your estimated timeline in publishing it in Nuget?

**Comment by daviddesmet** [comment]
It's already pushed and under validation, it will be available shortly (up to an hour) over [here](https://www.nuget.org/packages/Paseto.Core/0.7.2).
