### ISSUE TITLE
Bind Keys to Version and Purpose

### ISSUE THREAD

**Issue by paragonie-security** [daviddesmet/paseto-dotnet#47]
https://github.com/daviddesmet/paseto-dotnet/blob/db9d2b7b6b10c8494e42b7a84f77145dc3f0668a/src/Paseto/Protocol/Version2.cs#L96

https://github.com/daviddesmet/paseto-dotnet/blob/db9d2b7b6b10c8494e42b7a84f77145dc3f0668a/src/Paseto/Protocol/Version2.cs#L197

See https://github.com/paseto-standard/paseto-spec/blob/master/docs/02-Implementation-Guide/03-Algorithm-Lucidity.md

Right now, byte arrays are accepted by this API. There's no mechanism to prevent a user from using a v2 public key as a v2 local key.

**Comment by paragonie-security** [comment]
Bad bot.

**Comment by daviddesmet** [comment]
@paragonie-security FYI https://github.com/paragonie/paseto-io/pull/42
