### ISSUE TITLE
Remove dependency on Newtonsoft.Json

### ISSUE THREAD

**Issue by daviddesmet** [daviddesmet/paseto-dotnet#64]
As the title says, remove dependency on `Newtonsoft.Json` and replace it with `System.Text.Json`.

**Comment by grosch** [comment]
Any ETA on this, @daviddesmet ?

**Comment by daviddesmet** [comment]
@grosch I can do it in my lunchtime, it should be quick =)

**Comment by daviddesmet** [comment]
@grosch version [1.2.0](https://www.nuget.org/packages/Paseto.Core/1.2.0) released without Newtonsoft.Json

**Comment by grosch** [comment]
You rock, thank you!
